### ISSUE TITLE
Setpoint Identifier

### ISSUE THREAD

**Issue by JihadIsmail** [benripley/Arduino-Quadcopter#1]
Hello benripley, hope you are ok. first i want to thank you a lot for publishing your code, snd i want to ask at the PID Library about the definition of "setpoint" field is it the desired angle or desired throttle ?, and why modifying the values of (Ki & Kd) at SetSampleTime(newSampleTime) ? 
Thanks

**Comment by benripley** [comment]
Currently I am using it only to manage the orientation. In [PidController.ino](https://github.com/benripley/Arduino-Quadcopter/blob/master/Quadcopter/PidController.ino), you can see where a PID controller is defined for each of Roll, Pitch, and Yaw. A separate instance of a PID controller is used for each of these.

An understanding of how PID controllers work is necessary to understand what's going on here. The PID library could be used for any process variable that you want to control. That is not my library. It was written by [Brett Beauregard](https://github.com/br3ttb/Arduino-PID-Library) who wrote an excellent article on what you are asking about [here](http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/).
